import { quiz } from "./Deep Learning-Part 1"
export const data = [
    {
        id: 1,
        type: 'category 1',
        title: 'Photography',
        students: 200,
        rating: 4.1,
        image: 'https://www.eurodiaconia.org/wordpress/wp-content/uploads/2017/08/photography.jpeg',
        quiz: quiz,

    },
    {
        id: 2,
        type: 'category 1',
        title: 'Video Production',
        students: 200,
        rating: 4.1,
        image: 'https://www.breezpost.com/wp-content/uploads/2020/10/Video-Production-Company.jpg',
        quiz: quiz,
    },
    {
        id: 3,
        type: 'category 2',
        title: 'Adobe Lightroom',
        students: 200,
        rating: 4.1,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQO2MwKnZw8kbS9rmkPVzKeJJOau1EnPKTHUPEk4jXhZR4plJkh-s0obkR9WpIyetJyVA8&usqp=CAU',
        quiz: quiz,
    },
    {
        id: 4,
        type: 'category 1',
        title: 'Video Editing',
        students: 200,
        rating: 4.1,
        image: 'https://cdn.mos.cms.futurecdn.net/iiVac4HpTLWCc8La2iijRL.jpg',
        quiz: quiz,
    },
    {
        id: 5,
        type: 'category 1',
        title: 'Video Editing',
        students: 200,
        rating: 4.1,
        image: 'https://cdn.mos.cms.futurecdn.net/iiVac4HpTLWCc8La2iijRL.jpg',
        quiz: quiz,
    },
    {
        id: 6,
        type: 'category 1',
        title: 'Video Editing',
        students: 200,
        rating: 4.1,
        image: 'https://cdn.mos.cms.futurecdn.net/iiVac4HpTLWCc8La2iijRL.jpg',
        quiz: quiz,
    },
    {
        id: 7,
        type: 'category 1',
        title: 'Video Editing',
        students: 200,
        rating: 4.1,
        image: 'https://cdn.mos.cms.futurecdn.net/iiVac4HpTLWCc8La2iijRL.jpg',
        quiz: quiz,
    },
    {
        id: 8,
        type: 'category 3',
        title: 'Video Editing',
        students: 200,
        rating: 4.1,
        image: 'https://cdn.mos.cms.futurecdn.net/iiVac4HpTLWCc8La2iijRL.jpg',
        quiz: quiz,
    },
    {
        id: 9,
        type: 'category 1',
        title: 'Video Editing',
        students: 200,
        rating: 4.1,
        image: 'https://cdn.mos.cms.futurecdn.net/iiVac4HpTLWCc8La2iijRL.jpg',
        quiz: quiz,
    },
    {
        id: 10,
        type: 'category 2',
        title: 'Video Editing',
        students: 200,
        rating: 4.1,
        image: 'https://cdn.mos.cms.futurecdn.net/iiVac4HpTLWCc8La2iijRL.jpg',
        quiz: quiz,
    },
    {
        id: 11,
        type: 'category 2',
        title: 'Video Editing',
        students: 200,
        rating: 4.1,
        image: 'https://cdn.mos.cms.futurecdn.net/iiVac4HpTLWCc8La2iijRL.jpg',
        quiz: quiz,
    },
]